2024-03-23 15:35:27,627 [INFO] (main: 90): Mailbot开始运行并监听端口8080
2024-03-23 15:35:38,917 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:35:39,897 [INFO] (multi_apply: 16): 调用成功，总计尝试1次
2024-03-23 15:35:39,897 [INFO] (multi_apply: 17): 
2024-03-23 15:35:39,920 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:35:39,921 [ERROR] (multi_apply: 23): Command '['python3', 'send_mail.py', '231880291']' returned non-zero exit status 2.
2024-03-23 15:35:39,921 [ERROR] (multi_apply: 24): 发送邮件失败
2024-03-23 15:35:39,921 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:36:08,790 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:36:09,429 [INFO] (multi_apply: 16): 调用成功，总计尝试1次
2024-03-23 15:36:09,430 [INFO] (multi_apply: 17): 
2024-03-23 15:36:09,453 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:36:09,453 [ERROR] (multi_apply: 23): Command '['python3', 'send_mail.py', '231880291']' returned non-zero exit status 2.
2024-03-23 15:36:09,453 [ERROR] (multi_apply: 24): 发送邮件失败
2024-03-23 15:36:09,453 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:36:54,792 [INFO] (main: 90): Mailbot开始运行并监听端口8080
2024-03-23 15:36:55,344 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:36:56,180 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:36:56,180 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:36:56,180 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:36:56,180 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:37:03,282 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:37:04,221 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:37:04,222 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:37:04,222 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:37:04,222 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:37:05,414 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:37:06,410 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:37:06,410 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:37:06,410 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:37:06,410 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:37:13,227 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:37:14,554 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:37:14,554 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:37:14,554 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:37:14,554 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:39:02,923 [INFO] (main: 90): Mailbot开始运行并监听端口8080
2024-03-23 15:39:12,191 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:39:12,554 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:39:12,554 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:39:12,554 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:39:12,554 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:39:25,138 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:39:25,577 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:39:25,577 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:39:25,577 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:39:25,578 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:39:31,440 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:39:31,815 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:39:31,815 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:39:31,815 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:39:31,815 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:39:53,523 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:39:54,021 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:39:54,022 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:39:54,022 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:39:54,022 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:39:59,263 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:39:59,729 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:39:59,730 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:39:59,730 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:39:59,730 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:40:06,977 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:40:07,545 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:40:07,545 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:40:07,545 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:40:07,546 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:40:14,053 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:40:14,712 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:40:14,712 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:40:14,712 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:40:14,712 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:45:16,372 [INFO] (main: 90): Mailbot开始运行并监听端口8080
2024-03-23 15:45:24,706 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:45:25,577 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:45:25,577 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:45:25,577 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:45:25,578 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:45:39,857 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:45:40,625 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:45:40,626 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:45:40,626 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:45:40,626 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:45:55,277 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:45:56,042 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:45:56,042 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:45:56,042 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:45:56,042 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:46:11,707 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:46:12,488 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:46:12,488 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:46:12,488 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:46:12,489 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:55:27,686 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:55:27,942 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:55:27,942 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:55:27,942 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:55:27,942 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:55:50,120 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:55:50,369 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:55:50,370 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:55:50,370 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:55:50,370 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:56:17,408 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:56:17,666 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:56:17,667 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:56:17,667 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:56:17,667 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:56:27,646 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:56:27,904 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:56:27,904 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:56:27,904 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:56:27,904 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:56:43,803 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:56:43,825 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:56:43,825 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:56:43,825 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:56:43,825 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:56:45,140 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:56:45,163 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:56:45,163 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:56:45,163 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:56:45,163 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:56:46,085 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:56:46,108 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:56:46,108 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:56:46,108 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:56:46,108 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:56:48,719 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:56:48,742 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:56:48,742 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:56:48,742 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:56:48,742 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:57:14,006 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:57:14,031 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:57:14,031 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:57:14,031 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:57:14,032 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:57:15,126 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:57:15,147 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:57:15,147 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:57:15,147 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:57:15,147 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:57:16,134 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:57:16,156 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:57:16,157 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:57:16,157 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:57:16,157 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:57:18,037 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:57:18,059 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:57:18,059 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:57:18,060 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:57:18,060 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:57:22,132 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:57:22,155 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:57:22,155 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:57:22,155 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:57:22,155 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:57:50,061 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:57:50,085 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:57:50,086 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:57:50,086 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:57:50,086 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 15:58:01,313 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 15:58:01,595 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 15:58:01,595 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 15:58:01,595 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 15:58:01,596 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 16:00:43,664 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 16:00:43,929 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 16:00:43,929 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 16:00:43,929 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 16:00:43,930 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 16:00:46,982 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 16:00:47,237 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 16:00:47,238 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 16:00:47,238 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 16:00:47,238 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 16:00:48,962 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 16:00:49,216 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 16:00:49,216 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 16:00:49,216 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 16:00:49,216 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 16:00:50,876 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 16:00:51,142 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 16:00:51,142 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 16:00:51,142 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 16:00:51,142 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
2024-03-23 16:01:42,452 [ERROR] (email_request: 25): 收到一次发送邮件请求 user: 231880291
2024-03-23 16:01:42,709 [ERROR] (multi_apply: 22): 函数email_request.<locals>.<lambda>.<locals>.<lambda>第1次调用失败！
2024-03-23 16:01:42,710 [ERROR] (multi_apply: 23): Command '['python3', 'fetch.py', '231880291']' returned non-zero exit status 1.
2024-03-23 16:01:42,710 [ERROR] (multi_apply: 24): 获取资料失败
2024-03-23 16:01:42,710 [ERROR] (multi_apply: 25): 函数email_request.<locals>.<lambda>.<locals>.<lambda>调用失败, 完全退出
